<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Bank App</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c2d885c4-4e79-401e-8591-03aeae052c0a</testSuiteGuid>
   <testCaseLink>
      <guid>d952cc3e-196e-4cfe-b9f5-95c60ecb34f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Register</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2783b185-3760-4019-8781-d98b36447458</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a64e3054-687d-4812-be3c-2d99f1cfa3ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fc3da9d-4664-40e6-803b-8dbc85974214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74930659-7f85-4c47-af9a-5f45fafef56a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdbb0b3a-49e1-4f28-b9d6-0f8c4cf3ed35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b5ee1fa-80f1-44df-b619-784eb1536efb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MP-6 Gibran - TC_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8938619c-3251-42f8-b334-62c19fd0414c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf21e586-60e6-40c2-8d52-d350a3419b6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45f7dcb4-2f44-44c4-a433-2274329f0512</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Add Bank Account</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b6b8217c-3972-4dda-9959-8035f29e182d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/BankAccounts</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b6b8217c-3972-4dda-9959-8035f29e182d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountname</value>
         <variableId>14a29c22-fbac-4f1c-987f-5c5089ce4196</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b6b8217c-3972-4dda-9959-8035f29e182d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>initbalance</value>
         <variableId>ba8eb309-2f23-4463-a464-12aeebf8e2ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>593d516f-7737-46a0-876a-59ea22367af0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transfer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc04e488-22ae-408e-922b-70034e1b2418</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0851b21a-7d2d-42f8-91ee-22044d80b745</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c024bc87-4009-4f3b-9214-59995f3d5bf3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/BankAccounts</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5676b9ea-f392-462f-b644-2c3c75172544</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Add Payee</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5676b9ea-f392-462f-b644-2c3c75172544</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>payee</value>
         <variableId>d3b39d16-4fdf-4924-9f8f-52b9b02d5ab7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
